baseurl = "https://f3peakcity.com"
DefaultContentLanguage = "en"
title = "F3 Peak City"
#theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "G-Z265E06J10"

# Required for inlining iframes, divs, and other markup
# in the markdown (i.e. .md) files
[markup.goldmark.renderer]
unsafe = true

[module]
  proxy = "direct"  
  [module.hugoVersion]
    min = "0.104.2"
  [[module.imports]]
    path = "github.com/f3peakcity/beautifulhugo"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Fitness Fellowship Faith"
  mainSections = ["post","posts"]
  logo = "img/brand/f3-black-on-white-500x500.png" # Expecting square dimensions
  darkLogo = "img/brand/f3-white-on-black-500x500.png"
  favicon = "img/cropped-cropped-F3-Nation-Logo-White-with-Black-background-32x32.jpg"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

# Header Carosel
[[Params.bigimg]]
  src = "img/events/the-board-meeting_scaled.png"
  desc = "The Board Meeting"
[[Params.bigimg]]
  src = "img/events/New_Years_Day_2026_scaled.png"
  desc = "2026 New Years"
[[Params.bigimg]]
  src = "img/events/july-4th_scaled.png"
  #desc = "July 4th"
[[Params.bigimg]]
  src = "img/events/f3-dads-camp_scaled.png"
  desc = "F3 Dads Camp - Hanging Rock"
[[Params.bigimg]]
  src = "img/events/das-boot-bday_scaled.png"
  #desc = "Das Boot 5 Yr Anny"
[[Params.bigimg]]
  src = "img/events/das-boot_scaled.png"
  #desc = "Das Boot at the depot"
[[Params.bigimg]]
  src = "img/events/coffeteria_scaled.png"
  desc = "Common Grounds Coffeteria"
[[Params.bigimg]]
  src = "img/events/Christmas_Party_scaled.png"
  desc = "Christmas Party 2025 at Oaklyn Springs"
[[Params.bigimg]]
  src = "img/events/2023-peak-city-launch-water-tower-scaled_16x9.png"





#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[taxonomies]
  # keep default taxonomies
  category = 'categories'
  tag = 'tags'
  # new taxonomies for backblasts
  ao = 'AOs'
  pax = 'pax'

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
#   name = "Some Person"
#   website = "yourwebsite.com"
#   email = "youremail@domain.com"
  facebook = "f3peakcity"
  github = "f3peakcity"
#   gitlab = "username"
#   bitbucket = "username"
  twitter = "f3peakcity"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
  instagram = "f3peakcity"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"
#   codepen = "username"
#   mastodon = "url"
#   kaggle = "username"
#   weibo = "username"
  slack = "f3peakcity"
#   discord = "invite code (https://discord.gg/XXXXXXX)"
#   strava = "userid"

[[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    weight = 1

[[menu.main]]
    parent = "schedule"
    name = "Q Shop"
    url = "q/"
    weight = 2

[[menu.main]]
    parent = "schedule"
    name = "1st F (Fitness)"
    url = "schedule/"
    weight = 3

[[menu.main]]
    parent = "schedule"
    name = "2nd F (Fellowship)"
    url = "schedule/#2ndf"
    weight = 4

[[menu.main]]
    parent = "schedule"
    name = "3rd F (Faith)"
    url = "schedule/#3rdf"
    weight = 5

[[menu.main]]
    parent = "schedule"
    name = "Calendar of Events"
    url = "schedule/#events"
    weight = 6

[[menu.main]]
    identifier = "pax"
    name = "PAX"
    weight = 40

[[menu.main]]
    parent = "pax"
    name = "New to F3"
    url = "new-to-f3/"
    weight = 41

[[menu.main]]
    parent = "pax"
    name = "Leadership"
    url = "leadership/"
    weight = 42

[[menu.main]]
    parent = "pax"
    name = "Region stats"
    url = "https://pax-vault.f3nation.com/stats/region/40342"
    weight = 43

[[menu.main]]
    identifier = "contact"
    name = "Stay in touch"
    weight = 50

[[menu.main]]
    parent = "contact"
    name = "Slack"
    url = "slack/"
    weight = 51

[[menu.main]]
    parent = "contact"
    name = "Backblasts"
    url = "backblasts/"
    weight = 52

[[menu.main]]
    parent = "contact"
    name = "Articles"
    url = "articles/"
    weight = 53

[[menu.main]]
    parent = "contact"
    name = "Contact Us"
    url = "contact/"
    weight = 54
